Vet clinic database: add "join table" for visits
FrankMugagga/vet-clinic-database pull request #4
Opened 2023-05-26 20:34 UTC by FrankMugagga

### Activities
Created a table named vets
Established many-to-many relationship between the tables species and vets and created table specializations
Established a many-to-many relationship between the tables animals and vets and created a table visits
Inserted corresponding data in the created tables
Did queries that required joining the tables
Updated the REAME.md file

2023-05-26 20:47 UTC, Kamba56 reviewed
Hi @FrankMugagga

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly remove the Live demo section from your readme as it does not apply to this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-26 21:59 UTC, Kamba56 requested changes
Hi @FrankMugagga, 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great job adding a relationship between vets and species using the specialization table.!👏👏👏
- [x] Great job updating the tables. 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 21:59 UTC, Kamba56 commented on queries.sql
> + 'Maisy Smith' GROUP BY s.name ORDER BY total_visits DESC LIMIT 1;
- [ ] Kindly add screenshots of the results you got after running all queries to your PR. The screenshots will determine if you successfully ran all the queries and if the queries are correct.

2023-05-26 21:59 UTC, Kamba56 commented on queries.sql
> +vet_clinic=# SELECT animals.name, COUNT(visits.animals_id) AS Animal_visits FROM visits JOIN animals ON animals.id = animals_id JOIN vets ON vets.id = visits.vets_id GROUP BY animals.name ORDER BY An
- [ ] Remove all commented pieces of code from your documents to maintain a clean document.

2023-05-27 08:34 UTC, arslanbisharat commented
Hi @FrankMugagga,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 10:20 UTC, merged